language: node_js

node_js:
  - 6
  - 8
  - 10
  - 11

script: node_modules/.bin/istanbul cover node_modules/.bin/tape ./test/*

after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"

notifications:
  email:
    - lilleman@larvit.se
